{% set name = "unipy" %}
{% set version = "0.1.27" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9956c3b1c020af4ebf36437879924057eec351531d299c4c9a4b016a03038024

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - google-auth-oauthlib >=0.2.0
    - matplotlib >=2.0.2
    #- mglearn >=0.1.6
    - numpy >=1.13.1
    - numpydoc >=0.7.0
    - oauth2client >=4.1.2
    - pandas >=0.20.2
    - pandasql >=0.7.3
    - paramiko >=2.1.2
    - pip
    - pyasn1 >=0.4.3
    - pyasn1-modules >=0.2.1
    - pydrive >=1.2.1
    - python
    - scikit-image >=0.13.0
    - scikit-learn >=0.18.0
    - scipy >=0.19.1
    - seaborn >=0.8
    - statsmodels >=0.8.0
  run:
    - google-auth-oauthlib >=0.2.0
    - matplotlib >=2.0.2
    #- mglearn >=0.1.6
    - numpy >=1.13.1
    - numpydoc >=0.7.0
    - oauth2client >=4.1.2
    - pandas >=0.20.2
    - pandasql >=0.7.3
    - paramiko >=2.1.2
    - pyasn1 >=0.4.3
    - pyasn1-modules >=0.2.1
    - pydrive >=1.2.1
    - python
    - scikit-image >=0.13.0
    - scikit-learn >=0.18.0
    - scipy >=0.19.1
    - seaborn >=0.8
    - statsmodels >=0.8.0

test:
  imports:
    - unipy
    - unipy.core
    - unipy.dataset
    - unipy.image
    - unipy.math
    - unipy.plots
    - unipy.stats
    - unipy.tools
    - unipy.unipy_test
    - unipy.utils

about:
  home: https://unipy.readthedocs.io/en/latest/index.html
  license: MIT
  license_family: MIT
  license_file: 
  summary: Useful tools for Data Scientists
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
